apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  annotations:
    gateway.networking.k8s.io/generator: ingress2gateway-0.4.0
  name: "{{ .Release.Name }}"
spec:
  gatewayClassName: envoy-gateway
  listeners:
    - name: postgres-breeze-blocks-net-tcp
      port: 5432
      protocol: TCP
      tls:
        certificateRefs:
          - group: null
            kind: null
            name: postgres-tls
