---
# Source: postgresql/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres
  labels:
    helm.sh/chart: postgresql-0.0.2
    statefulset.kubernetes.io/name: postgresql
    statefulset.kubernetes.io/instance: postgresql
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    serviceaccount.kubernetes.io/name: postgres
automountServiceAccountToken: true
---
# Source: postgresql/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    helm.sh/chart: postgresql-0.0.2
    statefulset.kubernetes.io/name: postgresql
    statefulset.kubernetes.io/instance: postgresql
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    statefulset.kubernetes.io/name: postgresql
    statefulset.kubernetes.io/instance: postgresql
---
# Source: postgresql/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      helm.sh/chart: postgresql-0.0.2
      statefulset.kubernetes.io/name: postgresql
      statefulset.kubernetes.io/instance: postgresql
      app.kubernetes.io/version: "1.16.0"
      app.kubernetes.io/managed-by: Helm
  serviceName: "postgresql"
  replicas: 1
  template:
    metadata:
      labels:
        helm.sh/chart: postgresql-0.0.2
        statefulset.kubernetes.io/name: postgresql
        statefulset.kubernetes.io/instance: postgresql
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      containers:
        - name: postgres
          image: "postgres:16-alpine"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_DB
              value: "postgres"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: password
          volumeMounts:
            - name: postgresql
              mountPath: /var/lib/postgresql/
  volumeClaimTemplates:
    - metadata:
        name: postgresql
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
        storageClassName: csi-driver-lvm-linear
        volumeMode: Filesystem
---
# Source: postgresql/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "postgresql-test-connection"
  labels:
    helm.sh/chart: postgresql-0.0.2
    statefulset.kubernetes.io/name: postgresql
    statefulset.kubernetes.io/instance: postgresql
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['postgresql:5432']
  restartPolicy: Never
