---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  gatewayClassName: eg
  listeners:
    - name: {{ .Release.Name }}
      hostname: {{ .Values.service.hostname }}
      port: 9187
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
