---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: k8s01-sda
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  hostPath:
    path: "/srv/k8s/k8s01/volumes"
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    nautobot: postgres
    type: local
  name: nautobot-postgres
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 32Gi
  hostPath:
    path: "/srv/k8s/k8s01/volumes/nautobot/postgres"
  storageClassName: manual
