---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    nautobot-storage: static
    type: local
  name: nautobot-static
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: "/srv/k8s/k8s01/volumes/nautobot/static"
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    nautobot-storage: postgres
    type: local
  name: nautobot-postgres
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 32Gi
  hostPath:
    path: "/srv/k8s/k8s01/volumes/nautobot/postgres"
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    nautobot-storage: redis
    type: local
  name: nautobot-redis
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 8Gi
  hostPath:
    path: "/srv/k8s/k8s01/volumes/nautobot/redis"
  storageClassName: manual
