{{- if .Values.certmanager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  # Secret names are always required.
  secretName: {{ .Release.Name }}-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      {{- .Values.certmanager.organizations | toYaml | nindent 6 }}
  commonName: {{ .Values.certmanager.commonName }}
  isCA: {{ .Values.certmanager.isCA }}
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - digital signature
    - key encipherment
  # Set DNS names to the names of the Postgres hosts
  dnsNames:
    {{- .Values.certmanager.dnsNames | toYaml | nindent 4 }}
  issuerRef:
    {{- .Values.certmanager.issuerRef | toYaml | nindent 4 }}
  group: cert-manager.io
{{- end -}}
