{{- if .Values.persistence.claim.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    name: {{ .Values.persistence.name }}
  labels:
    {{- include "postgresql.selectorLabels" . | nindent 4 }}
  name: postgresql
  namespace: postgresql
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}
{{ end }}
