---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    app.kubernetes.io/name: {{ .Release.Name }}
  labels:
    secret.kubernetes.io/name: {{ .Release.Name }}
    secret.kubernetes.io/instance: {{ .Release.Name }}
  name: {{ .Release.Name }}
  namespace: postgresql
type: Opaque
data:
  password: {{ .Values.database.password | b64enc }}
  username: {{ .Values.database.username | b64enc }}
