apiVersion: v1
kind: Secret
data:
  password: {{ .Values.config.database.password | b64enc | quote }}
  username: {{ .Values.config.database.username | b64enc | quote }}
metadata:
  annotations:
    {{ .Values.podAnnotations | toYaml | nindent 4 }}
  labels:
    {{ include "postgresql.labels" . | nindent 4 }}
  name: {{ .Release.Name }}
  namespace: database
type: Opaque
