apiVersion: v1
kind: Secret
metadata:
  annotations:
    app.kubernetes.io/name: {{ .Release.Name }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
  name: {{ .Release.Name }}
type: Opaque
data:
  password: {{ .Values.database.password }}
  username: {{ .Values.database.username }}
