{{- if eq .Values.type "StatefulSet" -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "postgresql.selectorLabels" . | nindent 6 }}
  serviceName: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  template:
    metadata:
      labels:
        {{- include "postgresql.labels" . | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_DB
              value: "{{ .Values.database.name }}"
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: password
            - name: PGHOST
              value: "{{ .Values.database.host }}"
            - name:  PGSSLCERT
              value: /etc/pg/ssl/tls.crt
            - name: PGSSLKEY
              value: /etc/pg/ssl/tls.key
            - name:  PGSSLCERTMODE
              value: allow
            - name: PGSSLROOTCERT
              value: /etc/pg/ssl/ca.crt
          volumeMounts:
            - name: {{ .Release.Name }}
              mountPath: /var/lib/postgresql/
              readOnly: false
            - name: ssl
              mountPath: /etc/pg/
              readOnly: true
      volumes:
        - name: ssl
          secret:
            secretName: postgres-tls
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      nodeSelector:
        {{ .Values.nodeSelector | toYaml }}
      serviceAccountName: {{ .Release.Name }}
  volumeClaimTemplates:
    - metadata:
        name: {{ .Release.Name }}
        labels:
          {{- include "postgresql.labels" . | nindent 10 }}
      spec:
        accessModes:
          {{- .Values.persistence.accessModes | toYaml | nindent 10 }}
        resources:
          requests:
            storage: {{ .Values.resources.requests.storage }}
        storageClassName: {{ .Values.persistence.storageClass }}
{{- end -}}
