{{- if eq .Values.type "StatefulSet" -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.nameOverride }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "postgresql.selectorLabels" . | nindent 6 }}
  serviceName: {{ .Values.nameOverride }}
  replicas: {{ .Values.replicaCount }}
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  template:
    metadata:
      labels:
        {{- include "postgresql.labels" . | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_DB
              value: "{{ .Values.database.name }}"
            - name: POSTGRES_USER
              value: "{{ .Values.database.username }}"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-{{ .Release.Name }}
                  key: password
            - name:  PGSSLCERT
              value: /etc/pg/ssl/tls.crt
            - name: PGSSLKEY
              value: /etc/pg/ssl/tls.key
            - name:  PGSSLCERTMODE
              value: allow
            - name: PGSSLROOTCERT
              value: /etc/pg/ssl/ca.crt
          volumeMounts:
            - name: {{ .Values.nameOverride }}
              mountPath: /var/lib/postgresql/
              readOnly: false
            {{- if .Values.database.config.enabled }}
            {{- .Values.volumeMounts | toYaml | nindent 12 }}
            {{- end -}}
      {{- if .Values.database.config.enabled }}
      volumes:
        {{- .Values.volumes | toYaml | nindent 8 }}
      {{ end }}
      nodeSelector:
        {{ .Values.nodeSelector | toYaml }}
      serviceAccountName: {{ .Values.nameOverride }}
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.nameOverride }}
        labels:
          {{- include "postgresql.labels" . | nindent 10 }}
      spec:
        accessModes:
          {{- .Values.persistence.accessModes | toYaml | nindent 10 }}
        resources:
          limits:
            storage: {{ .Values.resources.limits.storage }}
          requests:
            storage: {{ .Values.resources.requests.storage }}
        storageClassName: {{ .Values.persistence.storageClass }}
{{- end -}}
