# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   labels:
#     name: nautobot-static
#     nautobot-storage: static
#     type: local
#   name: nautobot-static
# spec:
#   accessModes:
#     - ReadWriteMany
#   capacity:
#     storage: 1Gi
#   hostPath:
#     path: "/srv/k8s/k8s01/volumes/nautobot/static"
#   storageClassName: manual
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  volumeMode: Block
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   labels:
#     name: nautobot-redis
#     nautobot-storage: redis
#     type: local
#   name: nautobot-redis
# spec:
#   accessModes:
#     - ReadWriteMany
#   capacity:
#     storage: 8Gi
#   hostPath:
#     path: "/srv/k8s/k8s01/volumes/nautobot/redis"
#   storageClassName: manual
